#pragma once

#include "micro-task.h"
#include "region-move-task.h"
#include "long-move-task.h"
#include "build-task.h"
#include "build-observer-task.h"
#include "morph-task.h"
#include "morph-observer-task.h"
#include "train-task.h"
#include "train-observer-task.h"
#include "tech-task.h"
#include "tech-observer-task.h"
#include "upgrade-task.h"
#include "upgrade-observer-task.h"
#include "scout-task.h"
